// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK-1JpSbPjYvObTSnGWXqLypVU-F9F77g',
    appId: '1:548685989203:web:ac828a982e3286107e4da6',
    messagingSenderId: '548685989203',
    projectId: 'final2-a569f',
    authDomain: 'final2-a569f.firebaseapp.com',
    storageBucket: 'final2-a569f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3xaK2dIR-yA_tYGhSOp95i89Bf3wARpE',
    appId: '1:548685989203:android:6db53bdcd80967a87e4da6',
    messagingSenderId: '548685989203',
    projectId: 'final2-a569f',
    storageBucket: 'final2-a569f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhW-2l_H4sXLRL56mD8LbgOuQlOXGSilE',
    appId: '1:548685989203:ios:8873bda055f310227e4da6',
    messagingSenderId: '548685989203',
    projectId: 'final2-a569f',
    storageBucket: 'final2-a569f.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhW-2l_H4sXLRL56mD8LbgOuQlOXGSilE',
    appId: '1:548685989203:ios:5b70c53b9233bde67e4da6',
    messagingSenderId: '548685989203',
    projectId: 'final2-a569f',
    storageBucket: 'final2-a569f.appspot.com',
    iosBundleId: 'com.example.firebaseApp.RunnerTests',
  );
}
